theme: jekyll-theme-minimal
title: Prashanth Swaminathan
author: Prashanth Swaminathan
description: "-___-"
url: byteofprash.github.io
baseurl: ""

# Build settings
port: 4000
exclude: [  "README.md" ]

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Blog settings
permalink: /:year/:month/:title/
