title: Prashanth Swaminathan
author: Prashanth Swaminathan
description: "Thinker and tinkerer"
url: byteofprash.github.io/blog/
baseurl: ""

# Build settings
port: 4000
exclude: [  "README.md" ]

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Blog settings
#permalink: /:year/:month/:date/:title/
permalink: /:year/:month/:date/:title/

theme: jekyll-theme-minimal
